# Site settings
title: Crofton Medical Psychology
email: info@croftonmedpsych.com
description: "Psychiatric and Psychological assessments and treatment."
baseurl: ""
url: "http://www.croftonmedpsych.com"

# Build settings
markdown: kramdown
permalink: pretty
