# Site settings
title: Crofton Medical Psychology Limited
email: jane_mg@hotmail.com
description: "Psychiatric and Psychological assessments and treatment."
baseurl: ""
url: "http://louiechristie.github.io/croftonmedpsych"

# Build settings
markdown: kramdown
permalink: pretty
